spring:
  application:
    name: notification-service
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://admin:admin@localhost:27016/notificationDB?authSource=admin}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:myuser}
    password: ${RABBIT_PASSWORD:secret}

server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    metadata-map:
      version: v0.9
      region: eu-central

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info

springdoc:
  api-docs:
    path: /notifications/v3/api-docs
  swagger-ui:
    path: /notifications/swagger-ui.html