# Global Docker Compose File
name: LinkUp_Backend
services:
  rabbitmq:
    container_name: linkup_rabbimtq
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-secret}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-myuser}
    networks:
      - linkup-net
  global_cache:
    container_name: redis_global_cache
    image: redis:7.2.6
    ports:
      - 6379:6379
    volumes:
      - "redis_data:/data"
  global_mongo:
    container_name: mongo_global_db
    image: mongo:8.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-admin}
    volumes:
      - "mongo_data:/data/db"

volumes:
  elasticsearch_data:
  redis_data:
  mongo_data:

networks:
  linkup-net:
     external: true
