
services:
  app:
    build: .
    image: 1olelllka/linkup-notificationservice
    container_name: notification_server
    networks:
      - linkup-net
    ports:
      - "8003:8003"
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - PROFILE_HOST=host.docker.internal
      - MONGO_HOST=host.docker.internal
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=27017
      - JWT_SECRET=${JWT_SECRET}

networks:
  linkup-net:
    external: true