
services:
  app:
    build: .
    networks:
      - linkup-net
    ports:
      - "8001:8001"
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
      - NEO4J_URI=bolt://host.docker.internal:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=product_admin
      - SPRING_ELASTICSEARCH_URIS=elastic:9200
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=myuser
      - RABBIT_PASSWORD=secret
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6376
  database:
    container_name: profile_neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/neo4j-admin
      - NEO4J_server_memory_heap_max__size=2G
    volumes:
      - "neo4j_data:/data"
  cache:
    container_name: profile_cache
    image: redis:7.2.6
    ports:
      - 6376:6379
    volumes:
      - "redis_data:/data"
volumes:
  neo4j_data:
  redis_data:

networks:
  linkup-net:
    external: true