
services:
  database:
    container_name: profile_neo4j
    image: neo4j:5.26.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/product_admin
      - NEO4J_server_memory_heap_max__size=2G
    volumes:
      - "neo4j_data:/data"

volumes:
  neo4j_data: