
services:
  app:
    build: .
    image: 1olelllka/linkup-profileservice
    container_name: profile_server
    networks:
      - linkup-net
    ports:
      - "8001:8001"
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
      - NEO4J_URI=bolt://host.docker.internal:7687
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
volumes:
  neo4j_data:

networks:
  linkup-net:
    external: true