
services:
  database:
    container_name: profile_neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/neo4j-admin
      - NEO4J_server_memory_heap_max__size=2G
    volumes:
      - "neo4j_data:/data"
  cache:
    container_name: profile_cache
    image: redis:7.2.6
    ports:
      - 6376:6379
    volumes:
      - "redis_data:/data"
volumes:
  neo4j_data:
  redis_data: