# Generated by Django 5.2 on 2025-08-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.CharField(blank=True),
        ),
    ]
