# Generated by Django 5.2 on 2025-08-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_name_comment_photo_comment_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
