
services:
  app:
    build: .
    image: 1olelllka/linkup-chatservice
    container_name: chat_server
    ports:
      - "8005:8005"
    networks:
      - linkup-net
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=host.docker.internal
      - MONGO_PORT=27017
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - EUREKA_URI=http://eureka:8761/eureka
      - PROFILE_HOST=host.docker.internal
      - JWT_SECRET=${JWT_SECRET}
networks:
  linkup-net:
    external: true