server:
  port: 8004

spring:
  application:
    name: feed-service
  cloud:
    compatibility-verifier:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret

  data:
    redis:
      host: localhost
      port: 6377

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    metadata-map:
      version: v0.9
      region: eu-central

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      feed-service:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 75
        slowCallDurationThreshold: 2s
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        ignoreExceptions:
          - com.olelllka.feed_service.rest.exception.NotFoundException
          - com.olelllka.feed_service.rest.exception.AuthException