spring.application.name=discovery-server

server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=localhost

eureka.server.eviction-interval-times-in-ms=20000
eureka.server.enable-self-preservation=false